<?php

use Illuminate\Database\Seeder;

class InstitutionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('institutions')->delete();
        
        \DB::table('institutions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Colegio San Judas Tadeo',
                'type' => 'Educación Media y Básica',
                'phone' => '8093680055',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Martha Jiménez',
                'ador_one_phone' => '8099047413',
                'ador_one_email' => 'marthajimenezmale@hotmail.com',
                'ador_two_name' => 'Eliana Moisés',
                'ador_two_phone' => '8297620359',
                'ador_two_email' => 'emoisesc@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Colegio Domínico-Americano',
                'type' => 'Educación Media y Básica',
                'phone' => '8095350665',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Ana García',
                'ador_one_phone' => '8094817864',
                'ador_one_email' => 'anamar52e@gmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Secundaria Babeque',
                'type' => 'Educación Media y Básica',
                'phone' => '8093812673',
                'country' => 'República Dominicana',
                'ador_one_name' => 'María Victoria Suncar',
                'ador_one_phone' => '8493562395',
                'ador_one_email' => 'mariavictoriasuncar@gmail.com',
                'ador_two_name' => 'Dra. Julissa Gómez',
                'ador_two_phone' => '8096293557',
                'ador_two_email' => 'gomez_julissa@hotmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Colegio San Martín de Porres',
                'type' => 'Educación Media y Básica',
                'phone' => '8098074827',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Carlos Antonio Rosario García',
                'ador_one_phone' => '8092171932',
                'ador_one_email' => 'carlosr1777@hotmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Puntacana International School',
                'type' => 'Educación Media y Básica',
                'phone' => '8099593382',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Jossette Cuello',
                'ador_one_phone' => '8098818842',
                'ador_one_email' => 'cuellojossette@gmail.com',
                'ador_two_name' => 'Isabel Tejeda',
                'ador_two_phone' => '8092232847',
                'ador_two_email' => 'isabeltej@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Colegio Santa Teresita',
                'type' => 'Educación Media y Básica',
                'phone' => '8096876607',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Bélgica Paredes',
                'ador_one_phone' => '8099072601',
                'ador_one_email' => 'paredesbelgica@',
                'ador_two_name' => 'Karla Núñez Ávila',
                'ador_two_phone' => '8094963599',
                'ador_two_email' => 'canunes41@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'MC School',
                'type' => 'Educación Media y Básica',
                'phone' => '8095486620',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Cynthia Abreu',
                'ador_one_phone' => '8293171399',
                'ador_one_email' => 'c.abreu@mcschool.edu.do',
                'ador_two_name' => 'Lender Leyba',
                'ador_two_phone' => '8098587210',
                'ador_two_email' => 'l.leyba@mcschool.edu.do',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Mi Colegio',
                'type' => 'Educación Media y Básica',
                'phone' => '8095486555',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Cynthia Abreu',
                'ador_one_phone' => '8293171399',
                'ador_one_email' => 'c.abreu@mcschool.edu.do',
                'ador_two_name' => 'Lender Leyba',
                'ador_two_phone' => '8098587210',
                'ador_two_email' => 'l.leyba@mcschool.edu.do',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Santiago Christian School',
                'type' => 'Educación Media y Básica',
                'phone' => '8095706140',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Dinelsa Alberty',
                'ador_one_phone' => '8097536141',
                'ador_one_email' => 'dalberty@scs.edu.do',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Colegio Santa Teresa',
                'type' => 'Educación Media y Básica',
                'phone' => '8095948849',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Olga Silvestre',
                'ador_one_phone' => '8298906016',
                'ador_one_email' => 'osarah2927@gmail.com',
                'ador_two_name' => 'Bruno Belony',
                'ador_two_phone' => '8097777145',
                'ador_two_email' => 'belony18love@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Colegio Dominicano de La Salle',
                'type' => 'Educación Media y Básica',
            'phone' => '8096890111 (255)',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Martín Medina Pimentel',
                'ador_one_phone' => '8297131538',
                'ador_one_email' => 'martinmedpim@gmail.com',
                'ador_two_name' => 'Glenny Mateo',
                'ador_two_phone' => '8097565690',
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Colegio Nuestra Señora de La Paz',
                'type' => 'Educación Media y Básica',
                'phone' => '80953333233',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Gissel Rosario',
                'ador_one_phone' => '8493676972',
                'ador_one_email' => 'gissellrosario20@hotmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Cathedral International School',
                'type' => 'Educación Media y Básica',
                'phone' => '8095929997',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Guillermo Jorge',
                'ador_one_phone' => '8098614174',
                'ador_one_email' => 'gjorge3rd@gmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Colegio San Gabriel de la Dolorosa',
                'type' => 'Educación Media y Básica',
                'phone' => '8095356795',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Ramona González',
                'ador_one_phone' => '8292152206',
                'ador_one_email' => 'ramona_go@outlook.com',
                'ador_two_name' => 'Lidia Mota',
                'ador_two_phone' => '8299031020',
                'ador_two_email' => 'lidiavioleta_20@hotmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            14 => 
            array (
                'id' => 15,
            'name' => 'Colegio APEC Fernando Arturo de Meriño (CAFAM)',
                'type' => 'Educación Media y Básica',
            'phone' => '8096860021 (3236)',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Elizabeth Cirineo Cabrera',
                'ador_one_phone' => '8299287156',
                'ador_one_email' => 'cirineo.13@hotmail.com',
                'ador_two_name' => 'Daysis Mena',
                'ador_two_phone' => '8295987470',
                'ador_two_email' => 'lachefmena@hotmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-06 02:44:46',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'MI-EL Christian School',
                'type' => 'Educación Media y Básica',
                'phone' => '8094769346',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Rossy Báez',
                'ador_one_phone' => '8095010943',
                'ador_one_email' => 'baez.rossy@gmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => 'secondarycoord@mielschool.edu.do',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Instituto Montessori',
                'type' => 'Educación Media y Básica',
                'phone' => '8096877820',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Massielle Martínez',
                'ador_one_phone' => '8098019081',
                'ador_one_email' => 'masielle.martinez@gmail.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            17 => 
            array (
                'id' => 18,
            'name' => 'Centro Educativo Quisqueya de Santiago (CEQUISA)',
                'type' => 'Educación Media y Básica',
                'phone' => '8095751693, 8095755858',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Nora Ramírez',
                'ador_one_phone' => '8093456445',
                'ador_one_email' => 'colegioquisqueya@claro.net.do',
                'ador_two_name' => 'Anny Guzmán',
                'ador_two_phone' => '8295254618',
                'ador_two_email' => 'annysamir2010@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-05 21:02:09',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Saint Thomas School',
                'type' => 'Educación Media y Básica',
                'phone' => '8097325870',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Tania Borges',
                'ador_one_phone' => '8096976266',
                'ador_one_email' => 'borgesmartinez@hotmail.com',
                'ador_two_name' => 'Manuel Hazoury',
                'ador_two_phone' => NULL,
                'ador_two_email' => 'manuel3h@saintthomas.edu.do',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Saint George School',
                'type' => 'Educación Media y Básica',
                'phone' => '8095625262',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Firely Uribe Pagán',
                'ador_one_phone' => '8493580510',
                'ador_one_email' => 'furibe@saintgeorge.do',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Saint Joseph School',
                'type' => 'Educación Media y Básica',
                'phone' => '8095408992',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Luis Martínez',
                'ador_one_phone' => '8295705838',
                'ador_one_email' => 'lmartinez@sjs.edu.do',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Brilliant Minds School',
                'type' => 'Educación Media y Básica',
                'phone' => '8098069090, 8095925454',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Benedicta Calderón',
                'ador_one_phone' => '8093069090',
                'ador_one_email' => 'colegiobms@gmail.com',
                'ador_two_name' => 'Ana Satarria',
                'ador_two_phone' => '8093066191',
                'ador_two_email' => 'asatarria@gmail.com',
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Colegio Tilatá',
                'type' => 'Educación Media y Básica',
            'phone' => '5715921414 (122)',
                'country' => 'Colombia',
                'ador_one_name' => 'Sandra Arévalo Pérez',
                'ador_one_phone' => '573184935398',
                'ador_one_email' => 'sarevalo@colegiotilata.edu.co',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Colegio San Juan Bautista',
                'type' => 'Educación Media y Básica',
                'phone' => '8095816008',
                'country' => 'República Dominicana',
                'ador_one_name' => 'angela@colegiosanjuanbautista.com',
                'ador_one_phone' => '8494042360',
                'ador_one_email' => 'angela@colegiosanjuanbautista.com',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-04 21:20:51',
                'updated_at' => '2018-10-04 21:20:51',
            ),
            24 => 
            array (
                'id' => 25,
            'name' => 'Asociación Dominicana de las Naciones Unidas (ANU-RD)',
                'type' => 'Comité Organizador',
                'phone' => '8096859966',
                'country' => 'República Dominicana',
                'ador_one_name' => 'Rafael Valdivieso',
                'ador_one_phone' => '8296375626',
                'ador_one_email' => 'r.valdivieso@unadr.org.do',
                'ador_two_name' => NULL,
                'ador_two_phone' => NULL,
                'ador_two_email' => NULL,
                'created_at' => '2018-10-05 20:23:38',
                'updated_at' => '2018-10-05 20:23:38',
            ),
            25 => 
            array (
                'id' => 26,
            'name' => 'Fundación Global Democracia y Desarrollo (FUNGLODE)',
                'type' => 'Comité Organizador',
            'phone' => '80)6859966',
            'country' => 'República Dominicana',
            'ador_one_name' => NULL,
            'ador_one_phone' => NULL,
            'ador_one_email' => NULL,
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-05 20:24:36',
            'updated_at' => '2018-10-05 20:24:36',
        ),
        26 => 
        array (
            'id' => 27,
        'name' => 'Global Foundation for Democracy and Development (GFDD)',
            'type' => 'Comité Organizador',
            'phone' => '2022961840',
            'country' => 'Estados Unidos de America',
            'ador_one_name' => NULL,
            'ador_one_phone' => NULL,
            'ador_one_email' => NULL,
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-05 20:25:56',
            'updated_at' => '2018-10-05 20:25:56',
        ),
        27 => 
        array (
            'id' => 28,
            'name' => 'Globalmuners A. C.',
            'type' => 'Comité Organizador',
        'phone' => '+ 52 (55) 50.84.80.02',
            'country' => 'Mexico',
            'ador_one_name' => NULL,
            'ador_one_phone' => NULL,
            'ador_one_email' => NULL,
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-05 20:31:48',
            'updated_at' => '2018-10-05 20:31:48',
        ),
        28 => 
        array (
            'id' => 29,
            'name' => 'Colegio Calasanz Cúcuta',
            'type' => 'Educación Media y Básica',
            'phone' => '+57 5833332',
            'country' => 'Colombia',
            'ador_one_name' => 'Blanca Mery Rolón Rodríguez',
            'ador_one_phone' => '3002500405',
            'ador_one_email' => 'brolon@calasanzcucuta.edu.co',
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-06 03:07:21',
            'updated_at' => '2018-10-06 03:07:21',
        ),
        29 => 
        array (
            'id' => 30,
        'name' => 'Universidad APEC (UNAPEC)',
            'type' => 'Educación Superior',
            'phone' => NULL,
            'country' => 'República Dominicana',
            'ador_one_name' => NULL,
            'ador_one_phone' => NULL,
            'ador_one_email' => NULL,
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-06 04:10:01',
            'updated_at' => '2018-10-06 04:10:01',
        ),
        30 => 
        array (
            'id' => 31,
        'name' => 'Universidad del Caribe (UNICARIBE)',
            'type' => 'Educación Superior',
            'phone' => NULL,
            'country' => 'República Dominicana',
            'ador_one_name' => NULL,
            'ador_one_phone' => NULL,
            'ador_one_email' => NULL,
            'ador_two_name' => NULL,
            'ador_two_phone' => NULL,
            'ador_two_email' => NULL,
            'created_at' => '2018-10-06 04:11:24',
            'updated_at' => '2018-10-06 04:11:24',
        ),
    ));
        
        
    }
}