<?php

use Illuminate\Database\Seeder;

class ParticipantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('participants')->delete();
        
        \DB::table('participants')->insert(array (
            0 => 
            array (
                'id' => 2,
                'institution_id' => 10,
                'name' => 'Laura Marie',
                'lastname' => 'Herrera Gutiérrez',
                'email' => 'lauramherrerag@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Ensanche Las Américas, c/8 #72',
                'date_birth' => '2002-09-09',
                'cellphone' => '8493578909',
                'phone' => '8099895657',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Raquel Gutiérrez',
                'emergency_contact_cellphone' => '8099895657',
                'emergency_contact_phone' => '809861881',
                'emergency_contact_email' => 'gutierrezraquel27@gmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:07',
                'updated_at' => '2018-10-05 15:31:07',
            ),
            1 => 
            array (
                'id' => 3,
                'institution_id' => 10,
                'name' => 'Paula Maria',
                'lastname' => 'Cabrer Aguiar',
                'email' => 'paulamcabrer@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'San Isidro, Amanda 2, calle Central, Don lolo 3',
                'date_birth' => '2004-11-11',
                'cellphone' => '8092533470',
                'phone' => '8097660226',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Rosangela Aguiar',
                'emergency_contact_cellphone' => '8095432814',
                'emergency_contact_phone' => '8097660226',
                'emergency_contact_email' => 'rossaguiar@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:10',
                'updated_at' => '2018-10-05 15:31:10',
            ),
            2 => 
            array (
                'id' => 4,
                'institution_id' => 10,
                'name' => 'Michael Steven',
                'lastname' => 'Richardson Rivas',
                'email' => 'northkoreaonly@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'C/9 casa#9 Res. Amapola, Cancino',
                'date_birth' => '2001-03-07',
                'cellphone' => '829-803-0032',
                'phone' => '809-597-7736',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Elizabeth Rivas Lizardo',
                'emergency_contact_cellphone' => '809-383-0032',
                'emergency_contact_phone' => '809-597-7736',
                'emergency_contact_email' => 'elizabethrivas_31@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:14',
                'updated_at' => '2018-10-05 15:31:14',
            ),
            3 => 
            array (
                'id' => 5,
                'institution_id' => 10,
                'name' => 'Angel Gabriel',
                'lastname' => 'Torres Gomez',
                'email' => 'angeltorres0410@gmail.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Masculino',
                'academic_level' => 'Básica',
                'address' => 'calle H, numero 26 mendoza segunda',
                'date_birth' => '2005-10-04',
                'cellphone' => '8299803249',
                'phone' => '8095949149',
                'blood_type' => 'B+',
                'emergency_contact_name' => 'Lucy Gomez',
                'emergency_contact_cellphone' => '8096703249',
                'emergency_contact_phone' => '8095949149',
                'emergency_contact_email' => 'doctoragomez@gmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:16',
                'updated_at' => '2018-10-05 15:31:16',
            ),
            4 => 
            array (
                'id' => 6,
                'institution_id' => 10,
                'name' => 'Bianca',
                'lastname' => 'Ortíz',
                'email' => 'bianka-2002@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Calle Aruba #53. Ensanche Ozama, Santo Domingo Este.',
                'date_birth' => '1994-08-10',
                'cellphone' => '8297780139',
                'phone' => '8095918722',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Patria Pereyra',
                'emergency_contact_cellphone' => '8097690139',
                'emergency_contact_phone' => '8095918722',
                'emergency_contact_email' => 'patriapereyra@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:16',
                'updated_at' => '2018-10-05 15:31:16',
            ),
            5 => 
            array (
                'id' => 7,
                'institution_id' => 10,
                'name' => 'Laura Michelle',
                'lastname' => 'Diaz Silvestre',
                'email' => 'lauram0504@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Alma rosa 1 / calle costa rica / esq casi #9/ edif 152',
                'date_birth' => '2004-12-05',
                'cellphone' => '8294421309',
                'phone' => '8097884562',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Wanda Lucia',
                'emergency_contact_cellphone' => '8096799167',
                'emergency_contact_phone' => '8097884562',
                'emergency_contact_email' => 'wanda0504@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            6 => 
            array (
                'id' => 8,
                'institution_id' => 10,
                'name' => 'Hillary',
                'lastname' => 'Vargas',
                'email' => 'hillary.19.2002@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Básica',
                'address' => 'C/Puerto Rico #3 Ensanche Ozama',
                'date_birth' => '2002-06-19',
                'cellphone' => '829-985-2640',
                'phone' => '809-273-2530',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Pascual Vargas',
                'emergency_contact_cellphone' => '809-481-6356',
                'emergency_contact_phone' => '809-388-1005',
                'emergency_contact_email' => 'hvp.19.2002@gmail.com',
                'emergency_contact_relation' => 'Padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            7 => 
            array (
                'id' => 9,
                'institution_id' => 10,
                'name' => 'Francelis',
                'lastname' => 'Batista',
                'email' => 'francelisbatista07@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'calle Pedro A. Perez numero 12b',
                'date_birth' => '2004-09-27',
                'cellphone' => '829-629-4430',
                'phone' => '809-598-1599',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Aracelis Sosa',
                'emergency_contact_cellphone' => '809-449-0210',
                'emergency_contact_phone' => '809-598-1599',
                'emergency_contact_email' => 'arasosa20@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            8 => 
            array (
                'id' => 10,
                'institution_id' => 10,
                'name' => 'Karla Marí',
                'lastname' => 'Ramírez González',
                'email' => 'karlamariramirez@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Calle Palermo, Esq. Vaticano, urbanizacion Italia',
                'date_birth' => '2002-12-07',
                'cellphone' => '8499170576',
                'phone' => '8095985129',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Ana Teresa González Tapia',
                'emergency_contact_cellphone' => '8097505818',
                'emergency_contact_phone' => '8095945397',
                'emergency_contact_email' => 'anateresagonzalez26@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            9 => 
            array (
                'id' => 11,
                'institution_id' => 10,
                'name' => 'Farali',
                'lastname' => 'Cortorreal Javier',
                'email' => 'faralicortorreal001@gmail.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Femenino',
                'academic_level' => 'Básica',
                'address' => 'C/ Jardin del sur #6 esq. Alteza Real',
                'date_birth' => '2006-01-14',
                'cellphone' => '829-934-7624',
                'phone' => '809-595-3064',
                'blood_type' => 'O-',
                'emergency_contact_name' => 'Lizaida Javier Garrido',
                'emergency_contact_cellphone' => '829-308-1920',
                'emergency_contact_phone' => '809-595-3064',
                'emergency_contact_email' => 'javier.lizaida@gmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            10 => 
            array (
                'id' => 12,
                'institution_id' => 10,
                'name' => 'Yelissa Rosa',
                'lastname' => 'Díaz Ruíz',
                'email' => 'yelidruiz@icloud.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'C/Aruba #20, Ensanche Ozama.',
                'date_birth' => '2004-12-07',
                'cellphone' => '407-371-5159',
                'phone' => '809-592-6445',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Rosa Ruiz',
                'emergency_contact_cellphone' => '829-640-9234',
                'emergency_contact_phone' => '809-699-2549',
                'emergency_contact_email' => 'rosaruiz1430@gmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:18',
                'updated_at' => '2018-10-05 15:31:18',
            ),
            11 => 
            array (
                'id' => 13,
                'institution_id' => 10,
                'name' => 'Avril',
                'lastname' => 'Matos',
                'email' => 'avrilmatosc20@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'manzana 23 #16 El Brisal',
                'date_birth' => '2004-11-20',
                'cellphone' => '809-642-1120',
                'phone' => '809-593-0257',
                'blood_type' => 'B+',
                'emergency_contact_name' => 'Claritza Concepcion',
                'emergency_contact_cellphone' => '809-601-1411',
                'emergency_contact_phone' => '809-593-0257',
                'emergency_contact_email' => 'clarielis2001@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:19',
                'updated_at' => '2018-10-05 15:31:19',
            ),
            12 => 
            array (
                'id' => 14,
                'institution_id' => 10,
                'name' => 'Camila',
                'lastname' => 'Sosa',
                'email' => 'cs140344@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'C/Apostol Andre no100 ,Marbella 2 kl14 Auto Pista Las Americas .',
                'date_birth' => '2004-09-14',
                'cellphone' => '8293401601',
                'phone' => '8094811409',
                'blood_type' => 'A-',
                'emergency_contact_name' => 'Juana de la Rosa',
                'emergency_contact_cellphone' => '8094811409',
                'emergency_contact_phone' => 'Rolando Sosa',
                'emergency_contact_email' => 'rosadelarosa_j@hotmail.com',
                'emergency_contact_relation' => 'Padre y Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:19',
                'updated_at' => '2018-10-05 15:31:19',
            ),
            13 => 
            array (
                'id' => 15,
                'institution_id' => 10,
                'name' => 'Raynier Amin',
                'lastname' => 'Vargas Vargas',
                'email' => 'rayniervargas@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Alma Rosa I, Calle proyecto #17',
                'date_birth' => '2004-07-14',
                'cellphone' => '809-722-3848',
                'phone' => '809-788-3412',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Patricia Vargas',
                'emergency_contact_cellphone' => '809-880-5664',
                'emergency_contact_phone' => '809-788-3412',
                'emergency_contact_email' => 'cavarsa@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:19',
                'updated_at' => '2018-10-05 15:31:19',
            ),
            14 => 
            array (
                'id' => 16,
                'institution_id' => 10,
                'name' => 'Camila',
                'lastname' => 'Reyes Puello',
                'email' => 'camilareyespuello@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Juan Goico Alíz #58, Ensanche Ozama.',
                'date_birth' => '2004-05-19',
                'cellphone' => '8092172509',
                'phone' => '8096999043',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Rosa M. Puello',
                'emergency_contact_cellphone' => 'rosampuellotc@gmail.com',
                'emergency_contact_phone' => '809-280-2509',
                'emergency_contact_email' => 'rosampuellotc@gmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:20',
                'updated_at' => '2018-10-05 15:40:51',
            ),
            15 => 
            array (
                'id' => 17,
                'institution_id' => 10,
                'name' => 'Jaydalie',
                'lastname' => 'Medina Castillo',
                'email' => 'jaydaliedance@hotmail.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Femenino',
                'academic_level' => 'Básica',
                'address' => 'Calle Club de Leones, Casi esquina Sabana Larga, Residencial Gabriel, Alma Rosa 1',
                'date_birth' => '2005-08-29',
                'cellphone' => '809-416-0717',
                'phone' => '829-378-0407',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Yennelly Isobel Castillo',
                'emergency_contact_cellphone' => '1-809-717-9412',
                'emergency_contact_phone' => '829-378-0407',
                'emergency_contact_email' => 'Yennellyjaid@aol.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:26',
                'updated_at' => '2018-10-05 15:31:26',
            ),
            16 => 
            array (
                'id' => 18,
                'institution_id' => 10,
                'name' => 'Scarlette Massiel',
                'lastname' => 'Segura Sención',
                'email' => 'scarlettesegura123@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'C/Julio Cesar Martinez #06, Res. Gaby 1 apart. 403, Alma Rosa 1',
                'date_birth' => '2001-08-16',
                'cellphone' => '829-553-6173',
                'phone' => '809-594-8777',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Richard Anthony Segura Soler',
                'emergency_contact_cellphone' => '809-543-6173',
                'emergency_contact_phone' => '809-594-8777',
                'emergency_contact_email' => 'rsegura195@hotmail.com',
                'emergency_contact_relation' => 'Padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:27',
                'updated_at' => '2018-10-05 15:31:27',
            ),
            17 => 
            array (
                'id' => 19,
                'institution_id' => 10,
                'name' => 'Isabella',
                'lastname' => 'Báez',
                'email' => 'isabellapbaez@gmail.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Femenino',
                'academic_level' => 'Básica',
                'address' => 'Autopista de San Isidro, Claudio Peña #3',
                'date_birth' => '2005-12-07',
                'cellphone' => '809-341-2943',
                'phone' => '809-273-8647',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Ilka Hidalgo',
                'emergency_contact_cellphone' => '809-644-5644',
                'emergency_contact_phone' => '809-273-8647',
                'emergency_contact_email' => 'ilka.hidalgo@gmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:31:52',
                'updated_at' => '2018-10-05 15:31:52',
            ),
            18 => 
            array (
                'id' => 20,
                'institution_id' => 10,
                'name' => 'Christopher A.',
                'lastname' => 'Guerrero L.',
                'email' => 'caguerrerol@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'c/club activo 20-30, Ens. Ozama, #69, Santo Domingo Este.',
                'date_birth' => '2003-01-04',
                'cellphone' => '809-694-2908',
                'phone' => '809-595-2908',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Berenice Lantigua',
                'emergency_contact_cellphone' => 'alguerrero@claro.net.do',
                'emergency_contact_phone' => '809-350-2264',
                'emergency_contact_email' => 'alguerrero@claro.net.do',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:32:01',
                'updated_at' => '2018-10-05 15:35:59',
            ),
            19 => 
            array (
                'id' => 21,
                'institution_id' => 10,
                'name' => 'Pablo',
                'lastname' => 'Zironi',
                'email' => 'pabvizi01@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'calle 4ta, ens.Isabelita Residencial Antares #375, adentro del residencial el número de la casa es 35',
                'date_birth' => '2001-10-17',
                'cellphone' => '89-609-1580',
                'phone' => '809-599-2613',
                'blood_type' => 'O-',
                'emergency_contact_name' => 'Wilfredo Vilchez',
                'emergency_contact_cellphone' => '809-609-1580',
                'emergency_contact_phone' => '809-599-2613',
                'emergency_contact_email' => 'pabitoziro01@hotmail.com',
                'emergency_contact_relation' => 'Padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:32:10',
                'updated_at' => '2018-10-05 15:32:10',
            ),
            20 => 
            array (
                'id' => 22,
                'institution_id' => 10,
                'name' => 'Jolette',
                'lastname' => 'Matías',
                'email' => 'jolettemat@gmail.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Femenino',
                'academic_level' => 'Básica',
                'address' => 'Autopista San Isidro, Residencial Amanda 2',
                'date_birth' => '2006-02-04',
                'cellphone' => '1-809-853-9110',
                'phone' => '809-245-7389',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Julio Matías',
                'emergency_contact_cellphone' => '1-829-451-2141',
                'emergency_contact_phone' => '809-245-7389',
                'emergency_contact_email' => 'juliomat1973@gmail.com',
                'emergency_contact_relation' => 'Padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:34:53',
                'updated_at' => '2018-10-05 15:34:53',
            ),
            21 => 
            array (
                'id' => 23,
                'institution_id' => 10,
                'name' => 'Angel Eduardo',
                'lastname' => 'Oliva Sano',
                'email' => 'eduardo.oliva03@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Juan Isidro jimenez #38',
                'date_birth' => '2001-11-19',
                'cellphone' => '829 343 3435',
                'phone' => '809 596 3435',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Mayra Sano',
                'emergency_contact_cellphone' => '8093070040',
                'emergency_contact_phone' => '8095963435',
                'emergency_contact_email' => 'festin_de_colores@hotmail.com',
                'emergency_contact_relation' => 'madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:35:50',
                'updated_at' => '2018-10-05 15:35:50',
            ),
            22 => 
            array (
                'id' => 24,
                'institution_id' => 10,
                'name' => 'Darlenys Jazmín',
                'lastname' => 'Marte Martínez',
                'email' => 'darlenysmartemartinez@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'C/ Octavio Mejia Ricart esq. calle 10 Apt Merlot 205 B4',
                'date_birth' => '2002-10-11',
                'cellphone' => '829-649-3023',
                'phone' => '8095984422',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Jazmín Martínez',
                'emergency_contact_cellphone' => '829-350-3023',
                'emergency_contact_phone' => '809-350-3023',
                'emergency_contact_email' => 'martinez.yazgmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:39:33',
                'updated_at' => '2018-10-05 15:39:33',
            ),
            23 => 
            array (
                'id' => 25,
                'institution_id' => 10,
                'name' => 'Christian',
                'lastname' => 'Reynoso',
                'email' => 'dimitri19001@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Residencial Ébano',
                'date_birth' => '2002-12-19',
                'cellphone' => '829-491-5567',
                'phone' => '829-810-0410',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Ariangis Ramírez',
                'emergency_contact_cellphone' => '829-810-0487',
                'emergency_contact_phone' => '829-810-0497',
                'emergency_contact_email' => 'yuyu19star@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:40:33',
                'updated_at' => '2018-10-05 15:40:33',
            ),
            24 => 
            array (
                'id' => 26,
                'institution_id' => 10,
                'name' => 'Jean Carlos',
                'lastname' => 'Santana Medina',
                'email' => 'jeanMsantana09@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Calle K #35, Los Rosales',
                'date_birth' => '2000-11-08',
                'cellphone' => '809-250-1877',
                'phone' => '809-695-1783',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Marcia Medina',
                'emergency_contact_cellphone' => '809-749-8281',
                'emergency_contact_phone' => '809-695-1783',
                'emergency_contact_email' => 'scarlettesegura123@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:42:23',
                'updated_at' => '2018-10-05 15:42:23',
            ),
            25 => 
            array (
                'id' => 27,
                'institution_id' => 10,
                'name' => 'Jorge',
                'lastname' => 'Castro',
                'email' => 'jorgecastrop41@outlook.com',
                'category' => 'Delegado de Educación Básica',
                'gender' => 'Masculino',
                'academic_level' => 'Básica',
                'address' => 'calle club rotario 9 10 edificio pj 2c',
                'date_birth' => '2003-05-21',
                'cellphone' => '809 865 3301',
                'phone' => '809 594 0950',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'soraya polanco',
                'emergency_contact_cellphone' => '809 805 1761',
                'emergency_contact_phone' => '809 273 7027',
                'emergency_contact_email' => 'sorypolanco@hotmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:43:27',
                'updated_at' => '2018-10-05 15:43:27',
            ),
            26 => 
            array (
                'id' => 28,
                'institution_id' => 10,
                'name' => 'Mauro Junior',
                'lastname' => 'De Capitani Fernández',
                'email' => 'maurodecapitani2000@hotmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Alma Rosa I, Calle Máximo Ares García',
                'date_birth' => '2000-10-07',
                'cellphone' => '829-282-7632',
                'phone' => '8097889441',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Mauro',
                'emergency_contact_cellphone' => '849-285-1729',
                'emergency_contact_phone' => '809-682-1673',
                'emergency_contact_email' => 'decapi2004@hotmail.com',
                'emergency_contact_relation' => 'padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:43:36',
                'updated_at' => '2018-10-05 15:43:36',
            ),
            27 => 
            array (
                'id' => 29,
                'institution_id' => 10,
                'name' => 'Joan Manuel',
                'lastname' => 'Genao Salas',
                'email' => 'joanmgenao@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'calle octavio mejia ricard alma rosa 1',
                'date_birth' => '2006-05-14',
                'cellphone' => '849-353-7199',
                'phone' => '8095947199',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Michelle Salas',
                'emergency_contact_cellphone' => 'michelle.salas@gmail.com',
                'emergency_contact_phone' => '809-877-0858',
                'emergency_contact_email' => 'michelle.salas@gmail.com',
                'emergency_contact_relation' => 'Madre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:50:57',
                'updated_at' => '2018-10-05 15:51:41',
            ),
            28 => 
            array (
                'id' => 30,
                'institution_id' => 10,
                'name' => 'Camila',
                'lastname' => 'González Sánchez',
                'email' => 'camilagonzalezsanchez15@gmail.com',
                'category' => 'Delegado de Educación Media',
                'gender' => 'Femenino',
                'academic_level' => 'Media',
                'address' => 'Reparto los tres ojos, calle 8, casa #8',
                'date_birth' => '2003-10-31',
                'cellphone' => '8294232166',
                'phone' => '8096556757',
                'blood_type' => 'A-',
                'emergency_contact_name' => 'Fernando González Sánchez',
                'emergency_contact_cellphone' => '8294212527',
                'emergency_contact_phone' => '8096556757',
                'emergency_contact_email' => 'licfdogonzalez1215@hotmail.com',
                'emergency_contact_relation' => 'padre',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-05 15:50:57',
                'updated_at' => '2018-10-05 15:50:57',
            ),
            29 => 
            array (
                'id' => 31,
                'institution_id' => 25,
                'name' => 'Rafael',
                'lastname' => 'Valdivieso',
                'email' => 'r.valdivieso@unadr.org.do',
                'category' => 'Secretaría',
                'gender' => 'Masculino',
                'academic_level' => 'Media',
                'address' => 'Calle B, No. 10, Edif. Criscar I, Apto. 302, Ens. Serrallés, Santo Domingo',
                'date_birth' => '2000-01-06',
                'cellphone' => '8296375626',
                'phone' => '8095413987',
                'blood_type' => 'O+',
                'emergency_contact_name' => 'Rafael Valdivieso Genao',
                'emergency_contact_cellphone' => 'rvaldiviesogenao@gmail.com',
                'emergency_contact_phone' => '8095413987',
                'emergency_contact_email' => 'rvaldiviesogenao@gmail.com',
                'emergency_contact_relation' => 'Padre',
                'notes' => 'ANU-RD',
                'is_completed' => 0,
                'created_at' => '2018-10-05 21:05:33',
                'updated_at' => '2018-10-05 21:07:37',
            ),
            30 => 
            array (
                'id' => 32,
                'institution_id' => 25,
                'name' => 'Ignacio',
                'lastname' => 'Soriano',
                'email' => 'i.soriano@unadr.org.do',
                'category' => 'Secretaría',
                'gender' => 'Masculino',
                'academic_level' => 'Grado',
                'address' => 'La Esperilla',
                'date_birth' => '9999-09-09',
                'cellphone' => '8292170008',
                'phone' => '8292170008',
                'blood_type' => 'A+',
                'emergency_contact_name' => 'Genérico',
                'emergency_contact_cellphone' => 'Genérico',
                'emergency_contact_phone' => 'Genérico',
                'emergency_contact_email' => 'Genérico',
                'emergency_contact_relation' => 'Genérico',
                'notes' => NULL,
                'is_completed' => 0,
                'created_at' => '2018-10-06 01:11:42',
                'updated_at' => '2018-10-06 01:16:55',
            ),
        ));
        
        
    }
}